spring.application.name=HirePath
Spring.datasource.url=jdbc:mysql://localhost:3306/HirePath
Spring.datasource.username=root
Spring.datasource.password=root
Spring.jpa.hibernate.ddl-auto=update
Spring.jpa.show-sql=true
server.port=8081
adzuna.app.id=05fa7426
adzuna.app.key=84f3b784324db67159aaaf51fe40d1e5
